import { useEffect, useState } from 'react';
import api from '../../api/client.js';
import { EmptyState, ErrorAlert, Loading, StatusBadge, SuccessAlert, formatDate } from '../../components/Ui.jsx';

export function LawyerDashboardPage() {
  const [items, setItems] = useState(null); const [error, setError] = useState('');
  const load = () => api.get('/lawyer/consultations').then((res) => setItems(res.data.items)).catch((err) => setError(err.message));
  useEffect(() => { load(); }, []);
  const update = async (item, status, lawyerNote) => { setError(''); try { await api.patch(`/lawyer/consultations/${item._id}`, { status, lawyerNote }); await load(); } catch (err) { setError(err.message); } };
  return <section><p className="eyebrow">Lawyer dashboard</p><h1 className="text-4xl font-bold">Assigned requests</h1><div className="mt-7"><ErrorAlert message={error} />{!items ? <Loading /> : items.length ? <div className="grid gap-5">{items.map((item) => <LawyerRequest key={`${item._id}:${item.updatedAt}`} item={item} update={update} />)}</div> : <EmptyState title="No assigned requests" />}</div></section>;
}
function LawyerRequest({ item, update }) {
  const [status, setStatus] = useState(item.status === 'assigned' ? 'in-review' : item.status); const [note, setNote] = useState(item.lawyerNote || '');
  return <article className="card"><div className="flex flex-wrap justify-between gap-3"><div><div className="flex gap-3"><span className="font-mono text-xs text-slate-500">{item.reference}</span><StatusBadge value={item.status} /></div><h2 className="mt-2 text-xl font-bold">{item.subject}</h2><p className="mt-1 text-sm text-slate-500">{item.guestName} · {item.guestPhone} · {item.service?.title} · {formatDate(item.createdAt)}</p></div></div><p className="mt-4 rounded-xl bg-slate-50 p-4 text-sm leading-6">{item.details}</p>{!['resolved', 'cancelled'].includes(item.status) && <div className="mt-5 grid gap-4 lg:grid-cols-[200px_1fr_auto]"><label><span className="label">New status</span><select className="input" value={status} onChange={(e) => setStatus(e.target.value)}>{['in-review', 'scheduled', 'resolved'].map((value) => <option key={value}>{value}</option>)}</select></label><label><span className="label">Private lawyer note</span><input className="input" maxLength={3000} value={note} onChange={(e) => setNote(e.target.value)} /></label><button className="btn-primary self-end" onClick={() => update(item, status, note)}>Update</button></div>}</article>;
}

export function LawyerProfilePage() {
  const [profile, setProfile] = useState(null); const [services, setServices] = useState([]); const [status, setStatus] = useState({ error: '', success: '' });
  useEffect(() => { Promise.all([api.get('/lawyer/profile'), api.get('/public/services', { params: { limit: 50 } })]).then(([profileRes, serviceRes]) => { const item = profileRes.data.profile; setProfile({ ...item, services: item.services.map((service) => service._id), education: item.education.join(', '), languages: item.languages.join(', ') }); setServices(serviceRes.data.items); }).catch((err) => setStatus({ error: err.message, success: '' })); }, []);
  if (!profile) return <><ErrorAlert message={status.error} />{!status.error && <Loading />}</>;
  const update = (key, value) => setProfile({ ...profile, [key]: value });
  const submit = async (e) => { e.preventDefault(); try { await api.patch('/lawyer/profile', { ...profile, education: profile.education.split(',').map((v) => v.trim()).filter(Boolean), languages: profile.languages.split(',').map((v) => v.trim()).filter(Boolean) }); setStatus({ error: '', success: 'Lawyer profile updated.' }); } catch (error) { setStatus({ error: error.message, success: '' }); } };
  return <section><p className="eyebrow">Professional profile</p><h1 className="text-4xl font-bold">My lawyer profile</h1><form className="card mt-7 max-w-4xl" onSubmit={submit}><ErrorAlert message={status.error} /><SuccessAlert message={status.success} /><div className="grid gap-5 sm:grid-cols-2">{[['Designation', 'designation'], ['Experience years', 'experienceYears', 'number'], ['Consultation fee', 'consultationFee', 'number'], ['Chamber address', 'chamberAddress'], ['Education (comma separated)', 'education'], ['Languages (comma separated)', 'languages'], ['Photo URL', 'photoUrl', 'url']].map(([label, key, type = 'text']) => <label key={key}><span className="label">{label}</span><input className="input" type={type} value={profile[key] ?? ''} onChange={(e) => update(key, type === 'number' ? Number(e.target.value) : e.target.value)} /></label>)}<label className="sm:col-span-2"><span className="label">Services</span><select className="input min-h-32" multiple value={profile.services} onChange={(e) => update('services', Array.from(e.target.selectedOptions, (option) => option.value))}>{services.map((service) => <option key={service._id} value={service._id}>{service.title}</option>)}</select></label><label className="sm:col-span-2"><span className="label">Biography</span><textarea className="input min-h-40" value={profile.bio} onChange={(e) => update('bio', e.target.value)} /></label></div><button className="btn-primary mt-6">Save profile</button></form></section>;
}

export function LawyerBlogPage() {
  const [items, setItems] = useState(null); const [form, setForm] = useState({ title: '', category: '', excerpt: '', content: '' }); const [status, setStatus] = useState({ error: '', success: '' });
  const load = () => api.get('/lawyer/blog').then((res) => setItems(res.data.items)).catch((err) => setStatus({ error: err.message, success: '' })); useEffect(() => { load(); }, []);
  const submit = async (e) => { e.preventDefault(); try { const { data } = await api.post('/lawyer/blog', form); setForm({ title: '', category: '', excerpt: '', content: '' }); setStatus({ error: '', success: data.message }); await load(); } catch (error) { setStatus({ error: error.message, success: '' }); } };
  return <section><p className="eyebrow">Legal writing</p><h1 className="text-4xl font-bold">My blog drafts</h1><form className="card mt-7" onSubmit={submit}><h2 className="text-xl font-bold">Create a draft for admin review</h2><ErrorAlert message={status.error} /><SuccessAlert message={status.success} /><div className="mt-5 grid gap-5 sm:grid-cols-2"><label><span className="label">Title</span><input className="input" required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label><span className="label">Category</span><input className="input" required value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} /></label><label className="sm:col-span-2"><span className="label">Excerpt</span><textarea className="input" required maxLength={300} value={form.excerpt} onChange={(e) => setForm({ ...form, excerpt: e.target.value })} /></label><label className="sm:col-span-2"><span className="label">Article</span><textarea className="input min-h-48" required maxLength={30000} value={form.content} onChange={(e) => setForm({ ...form, content: e.target.value })} /></label></div><button className="btn-primary mt-5">Save draft</button></form><div className="mt-7">{items === null ? <Loading /> : items.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Title</th><th>Category</th><th>Date</th><th>Status</th></tr></thead><tbody>{items.map((item) => <tr key={item._id}><td className="font-semibold">{item.title}</td><td>{item.category}</td><td>{formatDate(item.createdAt)}</td><td><StatusBadge value={item.isPublished ? 'published' : 'draft'} /></td></tr>)}</tbody></table></div> : <EmptyState title="No blog drafts" />}</div></section>;
}
