import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../../api/client.js';
import { useAuth } from '../../context/AuthContext.jsx';
import { EmptyState, ErrorAlert, Loading, StatusBadge, SuccessAlert, formatDate } from '../../components/Ui.jsx';

export function ClientDashboardPage() {
  const [items, setItems] = useState(null); const [error, setError] = useState('');
  const load = () => api.get('/client/consultations').then((res) => setItems(res.data.items)).catch((err) => setError(err.message));
  useEffect(() => { load(); }, []);
  const cancel = async (id) => { if (!window.confirm('Cancel this pending request?')) return; try { await api.patch(`/client/consultations/${id}/cancel`); await load(); } catch (err) { setError(err.message); } };
  return <section><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Client dashboard</p><h1 className="text-4xl font-bold">My consultation requests</h1></div><Link className="btn-primary" to="/consultation">New request</Link></div><div className="mt-7"><ErrorAlert message={error} />{!items ? <Loading /> : items.length ? <div className="grid gap-5">{items.map((item) => <article className="card" key={item._id}><div className="flex flex-wrap justify-between gap-4"><div><div className="flex gap-3"><span className="font-mono text-xs text-slate-500">{item.reference}</span><StatusBadge value={item.status} /></div><h2 className="mt-2 text-xl font-bold">{item.subject}</h2><p className="mt-1 text-sm text-slate-500">{item.service?.title} · Submitted {formatDate(item.createdAt)}</p></div>{item.status === 'pending' && <button className="btn-danger self-start" onClick={() => cancel(item._id)}>Cancel</button>}</div><p className="mt-4 text-sm leading-6 text-slate-600">{item.details}</p>{item.assignedLawyer && <div className="mt-5 rounded-xl bg-sage p-4"><p className="text-xs font-bold uppercase tracking-wide text-forest">Assigned lawyer</p><p className="mt-1 font-bold">{item.assignedLawyer.user?.name}</p></div>}</article>)}</div> : <EmptyState title="No requests yet" text="Submit your first consultation request to get started." />}</div></section>;
}

export function ClientProfilePage() {
  const { user, updateProfile } = useAuth(); const [form, setForm] = useState({ name: user.name, phone: user.phone || '' }); const [status, setStatus] = useState({ saving: false, error: '', success: '' });
  const submit = async (e) => { e.preventDefault(); setStatus({ saving: true, error: '', success: '' }); try { await updateProfile(form); setStatus({ saving: false, error: '', success: 'Profile updated.' }); } catch (error) { setStatus({ saving: false, error: error.message, success: '' }); } };
  return <section className="max-w-2xl"><p className="eyebrow">Account</p><h1 className="text-4xl font-bold">My profile</h1><form className="card mt-7" onSubmit={submit}><ErrorAlert message={status.error} /><SuccessAlert message={status.success} /><label className="block"><span className="label">Full name</span><input className="input" required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label className="mt-5 block"><span className="label">Email</span><input className="input bg-slate-50" disabled value={user.email} /></label><label className="mt-5 block"><span className="label">Phone</span><input className="input" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></label><button className="btn-primary mt-6" disabled={status.saving}>{status.saving ? 'Saving…' : 'Save profile'}</button></form></section>;
}

export function ClientTestimonialsPage() {
  const [testimonials, setTestimonials] = useState(null); const [requests, setRequests] = useState([]); const [form, setForm] = useState({ consultation: '', rating: 5, comment: '' }); const [status, setStatus] = useState({ error: '', success: '' });
  const load = () => Promise.all([api.get('/client/testimonials'), api.get('/client/consultations')]).then(([reviews, consultationRes]) => { setTestimonials(reviews.data.items); setRequests(consultationRes.data.items); }).catch((err) => setStatus({ error: err.message, success: '' }));
  useEffect(() => { load(); }, []);
  const available = useMemo(() => requests.filter((request) => request.status === 'resolved' && !testimonials?.some((item) => item.consultation?._id === request._id)), [requests, testimonials]);
  const submit = async (e) => { e.preventDefault(); try { const { data } = await api.post('/client/testimonials', form); setForm({ consultation: '', rating: 5, comment: '' }); setStatus({ error: '', success: data.message }); await load(); } catch (error) { setStatus({ error: error.message, success: '' }); } };
  return <section><p className="eyebrow">Feedback</p><h1 className="text-4xl font-bold">My testimonials</h1><ErrorAlert message={status.error} /><SuccessAlert message={status.success} />{available.length > 0 && <form className="card mt-7" onSubmit={submit}><h2 className="text-xl font-bold">Review a resolved consultation</h2><div className="mt-5 grid gap-5 sm:grid-cols-[1fr_150px]"><label><span className="label">Consultation</span><select className="input" required value={form.consultation} onChange={(e) => setForm({ ...form, consultation: e.target.value })}><option value="">Choose…</option>{available.map((item) => <option key={item._id} value={item._id}>{item.reference} — {item.subject}</option>)}</select></label><label><span className="label">Rating</span><select className="input" value={form.rating} onChange={(e) => setForm({ ...form, rating: Number(e.target.value) })}>{[5, 4, 3, 2, 1].map((rating) => <option key={rating} value={rating}>{rating} / 5</option>)}</select></label></div><label className="mt-5 block"><span className="label">Comment</span><textarea className="input min-h-28" required value={form.comment} onChange={(e) => setForm({ ...form, comment: e.target.value })} /></label><button className="btn-primary mt-5">Submit for approval</button></form>}<div className="mt-7">{testimonials === null ? <Loading /> : testimonials.length ? <div className="grid gap-4">{testimonials.map((item) => <article className="card" key={item._id}><div className="flex justify-between"><p className="font-bold">{item.consultation?.subject}</p><StatusBadge value={item.isApproved ? 'approved' : 'review'} /></div><p className="mt-2 text-sm text-gold">{item.rating}/5 stars</p><p className="mt-3 text-slate-600">{item.comment}</p></article>)}</div> : <EmptyState title="No testimonials yet" />}</div></section>;
}
