import { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import api from '../../api/client.js';
import { useAuth } from '../../context/AuthContext.jsx';
import { ErrorAlert, SuccessAlert } from '../../components/Ui.jsx';

export default function ConsultationPage() {
  const { user } = useAuth(); const [params] = useSearchParams(); const [services, setServices] = useState([]); const [lawyers, setLawyers] = useState([]);
  const [form, setForm] = useState({ guestName: user?.name || '', guestEmail: user?.email || '', guestPhone: user?.phone || '', service: params.get('service') || '', preferredLawyer: params.get('lawyer') || '', subject: '', details: '', preferredDate: '' });
  const [status, setStatus] = useState({ loading: false, error: '', success: '' });
  useEffect(() => { Promise.all([api.get('/public/services', { params: { limit: 50 } }), api.get('/public/lawyers', { params: { limit: 50 } })]).then(([serviceRes, lawyerRes]) => { setServices(serviceRes.data.items); setLawyers(lawyerRes.data.items); }).catch((error) => setStatus({ loading: false, error: error.message, success: '' })); }, []);
  const update = (key) => (e) => setForm({ ...form, [key]: e.target.value });
  const submit = async (e) => { e.preventDefault(); setStatus({ loading: true, error: '', success: '' }); try { const { data } = await api.post('/consultations', form); setStatus({ loading: false, error: '', success: `${data.message} Reference: ${data.request.reference}` }); setForm({ ...form, subject: '', details: '', preferredDate: '' }); } catch (error) { setStatus({ loading: false, error: error.message, success: '' }); } };
  return <div className="section-pad"><div className="container-page max-w-4xl"><p className="eyebrow">Consultation request</p><h1 className="page-title">Tell us how we can help</h1><p className="mt-4 text-slate-600">A request is not an attorney-client agreement. The admin reviews and assigns it to a lawyer.</p><form onSubmit={submit} className="card mt-8"><ErrorAlert message={status.error} /><SuccessAlert message={status.success} /><div className="grid gap-5 sm:grid-cols-2"><Field label="Full name" value={form.guestName} onChange={update('guestName')} required disabled={Boolean(user)} /><Field label="Email" type="email" value={form.guestEmail} onChange={update('guestEmail')} required disabled={Boolean(user)} /><Field label="Phone" value={form.guestPhone} onChange={update('guestPhone')} required /><label><span className="label">Legal service</span><select className="input" value={form.service} onChange={update('service')} required><option value="">Choose a service</option>{services.map((item) => <option key={item._id} value={item._id}>{item.title}</option>)}</select></label><label><span className="label">Preferred lawyer (optional)</span><select className="input" value={form.preferredLawyer} onChange={update('preferredLawyer')}><option value="">No preference</option>{lawyers.map((item) => <option key={item._id} value={item._id}>{item.user?.name}</option>)}</select></label><Field label="Preferred date (optional)" type="date" value={form.preferredDate} onChange={update('preferredDate')} /></div><label className="mt-5 block"><span className="label">Subject</span><input className="input" value={form.subject} onChange={update('subject')} required maxLength={180} /></label><label className="mt-5 block"><span className="label">Brief case details</span><textarea className="input min-h-40" value={form.details} onChange={update('details')} required maxLength={5000} placeholder="Do not include highly sensitive evidence at this stage." /></label><button className="btn-primary mt-6" disabled={status.loading}>{status.loading ? 'Submitting…' : 'Submit request'}</button></form></div></div>;
}
function Field(props) { return <label><span className="label">{props.label}</span><input className="input" {...props} label={undefined} /></label>; }
