import { useState } from 'react';
import { Mail, MapPin, Phone } from 'lucide-react';
import api from '../../api/client.js';
import { ErrorAlert, SuccessAlert } from '../../components/Ui.jsx';

export default function ContactPage() {
  const [form, setForm] = useState({ name: '', email: '', phone: '', subject: '', message: '' }); const [status, setStatus] = useState({ loading: false, error: '', success: '' });
  const submit = async (e) => { e.preventDefault(); setStatus({ loading: true, error: '', success: '' }); try { const { data } = await api.post('/public/contact', form); setForm({ name: '', email: '', phone: '', subject: '', message: '' }); setStatus({ loading: false, error: '', success: data.message }); } catch (error) { setStatus({ loading: false, error: error.message, success: '' }); } };
  return <div className="section-pad"><div className="container-page grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><section><p className="eyebrow">Contact</p><h1 className="page-title">Let’s start a conversation</h1><p className="mt-5 leading-7 text-slate-600">For general questions, send a message. For a legal matter, use the consultation request form.</p><div className="mt-8 grid gap-4 text-sm"><p className="flex gap-3"><MapPin className="text-gold" />Bashundhara, Dhaka, Bangladesh</p><p className="flex gap-3"><Phone className="text-gold" />+880 1700-000000</p><p className="flex gap-3"><Mail className="text-gold" />hello@lexconnect.test</p></div></section><form className="card" onSubmit={submit}><ErrorAlert message={status.error} /><SuccessAlert message={status.success} /><div className="grid gap-5 sm:grid-cols-2"><Field label="Name" required value={form.name} onChange={(value) => setForm({ ...form, name: value })} /><Field label="Email" type="email" required value={form.email} onChange={(value) => setForm({ ...form, email: value })} /><Field label="Phone" value={form.phone} onChange={(value) => setForm({ ...form, phone: value })} /><Field label="Subject" required value={form.subject} onChange={(value) => setForm({ ...form, subject: value })} /></div><label className="mt-5 block"><span className="label">Message</span><textarea className="input min-h-36" required value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} /></label><button className="btn-primary mt-5" disabled={status.loading}>{status.loading ? 'Sending…' : 'Send message'}</button></form></div></div>;
}
function Field({ label, value, onChange, type = 'text', required }) { return <label><span className="label">{label}</span><input className="input" type={type} required={required} value={value} onChange={(e) => onChange(e.target.value)} /></label>; }
