import { useEffect, useState } from 'react';
import { BadgeCheck, MapPin, Search } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import api from '../../api/client.js';
import { EmptyState, ErrorAlert, Loading } from '../../components/Ui.jsx';

export function LawyersPage() {
  const [items, setItems] = useState([]); const [services, setServices] = useState([]); const [filters, setFilters] = useState({ q: '', service: '' }); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { api.get('/public/services', { params: { limit: 50 } }).then((res) => setServices(res.data.items)).catch((err) => setError(err.message)); }, []);
  useEffect(() => { const timer = setTimeout(() => { setLoading(true); api.get('/public/lawyers', { params: filters }).then((res) => setItems(res.data.items)).catch((err) => setError(err.message)).finally(() => setLoading(false)); }, 250); return () => clearTimeout(timer); }, [filters]);
  return <div className="section-pad"><div className="container-page"><p className="eyebrow">Lawyer directory</p><h1 className="page-title">Find the right legal professional</h1><div className="mt-8 grid max-w-3xl gap-3 sm:grid-cols-[1fr_260px]"><div className="relative"><Search className="absolute left-4 top-3.5 text-slate-400" size={20} /><input className="input pl-11" placeholder="Search name or expertise…" value={filters.q} onChange={(e) => setFilters({ ...filters, q: e.target.value })} /></div><select className="input" value={filters.service} onChange={(e) => setFilters({ ...filters, service: e.target.value })}><option value="">All services</option>{services.map((item) => <option key={item._id} value={item._id}>{item.title}</option>)}</select></div><div className="mt-8"><ErrorAlert message={error} />{loading ? <Loading /> : items.length ? <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{items.map((lawyer) => <Link className="card group" key={lawyer._id} to={`/lawyers/${lawyer.slug}`}><div className="flex h-20 w-20 items-center justify-center rounded-2xl bg-forest text-2xl font-bold text-white">{lawyer.user?.name?.split(' ').filter((word) => word.length > 2).slice(0, 2).map((word) => word[0]).join('')}</div><div className="mt-5 flex items-center gap-2"><h2 className="text-xl font-bold group-hover:text-forest">{lawyer.user?.name}</h2><BadgeCheck className="text-gold" size={18} /></div><p className="text-sm font-semibold text-gold">{lawyer.designation}</p><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">{lawyer.bio}</p><div className="mt-4 flex flex-wrap gap-2">{lawyer.services?.slice(0, 3).map((service) => <span key={service._id} className="rounded-full bg-sage px-2.5 py-1 text-xs font-semibold text-forest">{service.title}</span>)}</div></Link>)}</div> : <EmptyState title="No lawyers found" text="Try clearing the filters." />}</div></div></div>;
}

export function LawyerDetailPage() {
  const { identifier } = useParams(); const [data, setData] = useState(null); const [error, setError] = useState('');
  useEffect(() => { api.get(`/public/lawyers/${identifier}`).then((res) => setData(res.data)).catch((err) => setError(err.message)); }, [identifier]);
  if (error) return <div className="container-page section-pad"><ErrorAlert message={error} /></div>;
  if (!data) return <Loading />;
  const { lawyer, caseStudies } = data;
  return <div className="section-pad"><div className="container-page grid gap-8 lg:grid-cols-[340px_1fr]"><aside className="card self-start"><div className="flex h-28 w-28 items-center justify-center rounded-3xl bg-forest text-4xl font-bold text-white">{lawyer.user?.name?.split(' ').filter((word) => word.length > 2).slice(0, 2).map((word) => word[0]).join('')}</div><h1 className="mt-5 text-3xl font-bold">{lawyer.user?.name}</h1><p className="font-semibold text-gold">{lawyer.designation}</p><p className="mt-5 flex gap-2 text-sm text-slate-600"><MapPin size={18} />{lawyer.chamberAddress || 'Dhaka, Bangladesh'}</p><div className="mt-6 border-t pt-5"><p className="text-sm text-slate-500">Consultation fee</p><p className="text-2xl font-bold">৳{lawyer.consultationFee?.toLocaleString()}</p></div><Link className="btn-primary mt-6 w-full" to={`/consultation?lawyer=${lawyer._id}`}>Request consultation</Link></aside><main className="space-y-6"><section className="card"><h2 className="text-2xl font-bold">Professional profile</h2><p className="mt-4 whitespace-pre-line leading-8 text-slate-700">{lawyer.bio}</p><dl className="mt-7 grid gap-5 border-t pt-6 sm:grid-cols-2"><div><dt className="text-sm text-slate-500">Experience</dt><dd className="font-bold">{lawyer.experienceYears} years</dd></div><div><dt className="text-sm text-slate-500">Bar Council no.</dt><dd className="font-bold">{lawyer.barCouncilNumber}</dd></div><div><dt className="text-sm text-slate-500">Languages</dt><dd className="font-bold">{lawyer.languages?.join(', ')}</dd></div><div><dt className="text-sm text-slate-500">Education</dt><dd className="font-bold">{lawyer.education?.join(' · ')}</dd></div></dl></section><section className="card"><h2 className="text-2xl font-bold">Practice areas</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{lawyer.services.map((service) => <Link className="rounded-xl bg-sage p-4 font-bold text-forest" key={service._id} to={`/services/${service.slug || service._id}`}>{service.title}</Link>)}</div></section>{caseStudies.length > 0 && <section className="card"><h2 className="text-2xl font-bold">Case studies</h2>{caseStudies.map((item) => <Link className="mt-5 block border-t pt-5" key={item._id} to={`/case-studies/${item.slug}`}><h3 className="font-bold text-forest">{item.title}</h3><p className="mt-1 text-sm text-slate-600">{item.summary}</p></Link>)}</section>}</main></div></div>;
}
