import { useEffect, useState } from 'react';
import { ArrowRight, Search } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import api from '../../api/client.js';
import { EmptyState, ErrorAlert, Loading } from '../../components/Ui.jsx';

export function ServicesPage() {
  const [items, setItems] = useState([]); const [q, setQ] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { const timer = setTimeout(() => { setLoading(true); api.get('/public/services', { params: { q } }).then((res) => setItems(res.data.items)).catch((err) => setError(err.message)).finally(() => setLoading(false)); }, 250); return () => clearTimeout(timer); }, [q]);
  return <div className="section-pad"><div className="container-page"><p className="eyebrow">Practice areas</p><h1 className="page-title">How can we help?</h1><p className="mt-4 max-w-2xl text-lg text-slate-600">Browse practical legal services and connect each matter to an appropriate lawyer.</p><div className="relative mt-8 max-w-xl"><Search className="absolute left-4 top-3.5 text-slate-400" size={20} /><input className="input pl-11" value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search services…" /></div><div className="mt-8"><ErrorAlert message={error} />{loading ? <Loading /> : items.length ? <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{items.map((item) => <Link className="card group" key={item._id} to={`/services/${item.slug}`}><span className="text-xs font-bold uppercase tracking-wider text-gold">{item.category}</span><h2 className="mt-3 text-2xl font-bold group-hover:text-forest">{item.title}</h2><p className="mt-3 leading-7 text-slate-600">{item.summary}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-forest">View service <ArrowRight size={16} /></span></Link>)}</div> : <EmptyState title="No services found" text="Try a different search phrase." />}</div></div></div>;
}

export function ServiceDetailPage() {
  const { identifier } = useParams(); const [data, setData] = useState(null); const [error, setError] = useState('');
  useEffect(() => { api.get(`/public/services/${identifier}`).then((res) => setData(res.data)).catch((err) => setError(err.message)); }, [identifier]);
  if (error) return <div className="container-page section-pad"><ErrorAlert message={error} /></div>;
  if (!data) return <Loading />;
  const { service, lawyers, caseStudies } = data;
  return <><section className="bg-ink py-20 text-white"><div className="container-page"><p className="eyebrow">{service.category}</p><h1 className="page-title !text-white">{service.title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-white/70">{service.summary}</p><Link className="btn-primary mt-8 !bg-gold !text-ink" to={`/consultation?service=${service._id}`}>Request this service</Link></div></section><section className="section-pad"><div className="container-page grid gap-10 lg:grid-cols-[1fr_340px]"><article className="card"><h2 className="text-2xl font-bold">About this service</h2><p className="mt-5 whitespace-pre-line leading-8 text-slate-700">{service.description}</p></article><aside><h2 className="text-2xl font-bold">Lawyers for this service</h2><div className="mt-5 grid gap-4">{lawyers.map((lawyer) => <Link className="card !p-4" key={lawyer._id} to={`/lawyers/${lawyer.slug}`}><p className="font-bold">{lawyer.user?.name}</p><p className="text-sm text-gold">{lawyer.designation}</p><p className="mt-2 text-xs text-slate-500">{lawyer.experienceYears} years experience</p></Link>)}{!lawyers.length && <p className="text-slate-500">No lawyer assigned yet.</p>}</div></aside></div>{caseStudies.length > 0 && <div className="container-page mt-12"><h2 className="text-3xl font-bold">Related case studies</h2><div className="mt-5 grid gap-5 md:grid-cols-2">{caseStudies.map((item) => <Link className="card" to={`/case-studies/${item.slug}`} key={item._id}><h3 className="text-xl font-bold">{item.title}</h3><p className="mt-3 text-slate-600">{item.summary}</p></Link>)}</div></div>}</section></>;
}
